../rtl/spi_slave_simple_2.sv
../tb_slave/top/top_slave.sv
../tb_slave/if/spi_if.sv
../tb_slave/agent/spi_seq_item.sv
../tb_slave/agent/spi_sequencer.sv
../tb_slave/agent/spi_driver.sv
../tb_slave/agent/spi_monitor.sv
../tb_slave/agent/spi_agent.sv
../tb_slave/sequences/spi_simple_rx_sequence.sv
../tb_slave/sequences/spi_mode_test_sequence.sv
../tb_slave/sequences/spi_cs_check_sequence.sv
../tb_slave/sequences/spi_miso_test_sequence.sv
../tb_slave/env/spi_virtual_sequencer.sv
../tb_slave/sequences/spi_virtual_sequence.sv
../tb_slave/env/spi_cov.sv
../tb_slave/env/spi_refmod.sv
../tb_slave/env/spi_scb.sv
../tb_slave/env/spi_env.sv
../tb_slave/test/spi_base_test.sv
../tb_slave/test/spi_full_test.sv
../tb_slave/spi_assertions.sv
