../rtl/spi_master_simple.sv
../rtl/spi_slave_simple.sv
../tb_slave/top/top_slave.sv
../tb_slave/if/spi_if.sv
../tb_slave/agent/spi_transaction.sv
../tb_slave/agent/spi_sequencer.sv
../tb_slave/agent/spi_driver.sv
../tb_slave/agent/spi_monitor.sv
../tb_slave/agent/spi_monitor_in.sv
../tb_slave/agent/spi_agent.sv
../tb_slave/sequences/spi_simple_tx_sequence.sv
../tb_slave/env/spi_virtual_sequencer.sv
../tb_slave/sequences/spi_virtual_sequence.sv
../tb_slave/env/spi_cov.sv
../tb_slave/env/spi_refmod.sv
../tb_slave/env/spi_scb.sv
../tb_slave/env/spi_env.sv
../tb_slave/test/spi_base_test.sv
../tb_slave/test/spi_full_test.sv
